# -*- coding: utf-8 -*-

nawawi_items = """            DzikirItem(
                id = "nawawi_01",
                category = DzikirCategory.HIZIB_NAWAWI,
                orderNumber = 1,
                title = "Hizib An-Nawawi - Bagian 1: Alfa Alfi Hauqalah Bertingkat & Pengikat Diri",
                arabicText = "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\\nبِسْمِ اللَّهِ، اللَّهُ أَكْبَرُ، أَقُولُ عَلَىٰ نَفْسِي وَعَلَىٰ دِينِي، وَعَلَىٰ أَهْلِي، وَعَلَىٰ أَوْلَادِي، وَعَلَىٰ مَالِي، وَعَلَىٰ أَصْحَابِي، وَعَلَىٰ أَدْيَانِهِمْ، وَعَلَىٰ أَمْوَالِهِمْ، أَلْفَ مَرَّةٍ: لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ.\\nبِسْمِ اللَّهِ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، أَقُولُ عَلَىٰ نَفْسِي وَعَلَىٰ دِينِي، وَعَلَىٰ أَهْلِي، وَعَلَىٰ أَوْلَادِي، وَعَلَىٰ مَالِي، وَعَلَىٰ أَصْحَابِي، وَعَلَىٰ أَدْيَانِهِمْ، وَعَلَىٰ أَمْوَالِهِمْ، أَلْفَ أَلْفِ مَرَّةٍ: لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ.\\nبِسْمِ اللَّهِ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، أَقُولُ عَلَىٰ نَفْسِي وَعَلَىٰ دِينِي، وَعَلَىٰ أَهْلِي، وَعَلَىٰ أَوْلَادِي، وَعَلَىٰ مَالِي، وَعَلَىٰ أَصْحَابِي، وَعَلَىٰ أَدْيَانِهِمْ، وَعَلَىٰ أَمْوَالِهِمْ، أَلْفَ أَلْفِ أَلْفِ مَرَّةٍ: لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ",
                tajwidTags = "بِسْمِ اللَّهِ [l[ال]][l[رَّ]]حْمَٰنِ [l[ال]][p[رَّحِيمِ]]\\nبِسْمِ اللَّهِ، اللَّهُ [q[أَكْ]]بَرُ، [o[أَقُولُ]] عَلَىٰ نَفْسِي [o[وَعَلَىٰ]] دِينِي، [o[وَعَلَىٰ]] [o[أَهْلِي]]، [o[وَعَلَىٰ]] [o[أَوْلَادِي]]، [o[وَعَلَىٰ]] مَالِي، [o[وَعَلَىٰ]] [o[أَصْ]]حَابِي، [o[وَعَلَىٰ]] [o[أَدْيَانِهِمْ]]، [o[وَعَلَىٰ]] [o[أَمْوَالِهِمْ]]، [o[أَلْفَ]] [o[مَرَّةٍ]]: [o[لَا]] حَوْلَ وَلَا قُوَّةَ [o[إِلَّا]] بِاللَّهِ الْعَلِيِّ [p[الْعَظِيمِ]].\\nبِسْمِ اللَّهِ، اللَّهُ [q[أَكْ]]بَرُ، اللَّهُ [q[أَكْ]]بَرُ، [o[أَقُولُ]] عَلَىٰ نَفْسِي [o[وَعَلَىٰ]] دِينِي، [o[وَعَلَىٰ]] [o[أَهْلِي]]، [o[وَعَلَىٰ]] [o[أَوْلَادِي]]، [o[وَعَلَىٰ]] مَالِي، [o[وَعَلَىٰ]] [o[أَصْ]]حَابِي، [o[وَعَلَىٰ]] [o[أَدْيَانِهِمْ]]، [o[وَعَلَىٰ]] [o[أَمْوَالِهِمْ]]، [o[أَلْفَ]] [o[أَلْفِ]] [o[مَرَّةٍ]]: [o[لَا]] حَوْلَ وَلَا قُوَّةَ [o[إِلَّا]] بِاللَّهِ الْعَلِيِّ [p[الْعَظِيمِ]].\\nبِسْمِ اللَّهِ، اللَّهُ [q[أَكْ]]بَرُ، اللَّهُ [q[أَكْ]]بَرُ، اللَّهُ [q[أَكْ]]بَرُ، [o[أَقُولُ]] عَلَىٰ نَفْسِي [o[وَعَلَىٰ]] دِينِي، [o[وَعَلَىٰ]] [o[أَهْلِي]]، [o[وَعَلَىٰ]] [o[أَوْلَادِي]]، [o[وَعَلَىٰ]] مَالِي، [o[وَعَلَىٰ]] [o[أَصْ]]حَابِي، [o[وَعَلَىٰ]] [o[أَدْيَانِهِمْ]]، [o[وَعَلَىٰ]] [o[أَمْوَالِهِمْ]]، [o[أَلْفَ]] [o[أَلْفِ]] [o[أَلْفِ]] [o[مَرَّةٍ]]: [o[لَا]] حَوْلَ وَلَا قُوَّةَ [o[إِلَّا]] بِاللَّهِ الْعَلِيِّ [p[الْعَظِيمِ]]",
                transliteration = "Bismillāhir-raḥmānir-raḥīm. Bismillāh, Allāhu Akbar, aqūlu ‘alā nafsī wa ‘alā dīnī, wa ‘alā ahlī, wa ‘alā aulādī, wa ‘alā mālī, wa ‘alā aṣ-ḥābī, wa ‘alā adyānihim, wa ‘alā amwālihim, alfa marrah: Lā ḥaula wa lā quwwata illā billāhil-‘aliyyil-‘aẓīm. Bismillāh, Allāhu Akbar, Allāhu Akbar, aqūlu ‘alā nafsī... alfa alfi marrah: Lā ḥaula wa lā quwwata illā billāhil-‘aliyyil-‘aẓīm. Bismillāh, Allāhu Akbar, Allāhu Akbar, Allāhu Akbar, aqūlu ‘alā nafsī... alfa alfi alfi marrah: Lā ḥaula wa lā quwwata illā billāhil-‘aliyyil-‘aẓīm.",
                translationId = "Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang. Dengan nama Allah, Allah Mahabesar. Aku ucapkan (sebagai perlindungan) atas diriku, agamaku, keluargaku, anak-anakku, hartaku, para sahabatku, agama mereka, dan harta-harta mereka sebanyak seribu kali: 'Tiada daya dan tiada kekuatan melainkan dengan pertolongan Allah Yang Mahatinggi lagi Mahaagung'... sebanyak sejuta kali... dan sebanyak semiliar kali 'La hawla wa la quwwata illa billahil 'aliyyil 'adzim'.",
                translationEn = "In the name of Allah, Allah is the Greatest. I recite over myself, my faith, my family, my children, my wealth, and my companions a thousand times: 'There is no power nor might except by Allah the High, the Great'... a million times... a billion times...",
                repeatCount = 1,
                sourceNote = "Hizib An-Nawawi Al-Imam Yahya bin Syaraf An-Nawawi",
                fadhilah = "Membentengi diri, anak keturunan, harta benda, dan sahabat dengan jutaan perisai hauqalah dari marabahaya."
            ),
            DzikirItem(
                id = "nawawi_02",
                category = DzikirCategory.HIZIB_NAWAWI,
                orderNumber = 2,
                title = "Hizib An-Nawawi - Bagian 2: Bismillāhi wa Billāh & Asma Rabbis-Samawat",
                arabicText = "بِسْمِ اللَّهِ، وَبِاللَّهِ، وَمِنَ اللَّهِ، وَإِلَى اللَّهِ، وَعَلَى اللَّهِ، وَفِي اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ. بِسْمِ اللَّهِ عَلَىٰ دِينِي وَعَلَىٰ نَفْسِي وَعَلَىٰ أَوْلَادِي، بِسْمِ اللَّهِ عَلَىٰ مَالِي وَعَلَىٰ أَهْلِي، بِسْمِ اللَّهِ عَلَىٰ كُلِّ شَيْءٍ أَعْطَانِيهِ رَبِّي. بِسْمِ اللَّهِ رَبِّ السَّمَاوَاتِ السَّبْعِ وَرَبِّ الْأَرَضِينَ السَّبْعِ وَرَبِّ الْعَرْشِ الْعَظِيمِ. بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ (٣ مرات). بِسْمِ اللَّهِ خَيْرِ الْأَسْمَاءِ فِي الْأَرْضِ وَفِي السَّمَاءِ، بِسْمِ اللَّهِ افْتَتَحْتُ وَبِهِ أَخْتَتِمُ، وَعَلَى اللَّهِ تَوَكَّلْتُ",
                tajwidTags = "بِسْمِ اللَّهِ، وَبِاللَّهِ، وَمِنَ اللَّهِ، [o[وَإِلَى]] اللَّهِ، [o[وَعَلَى]] اللَّهِ، وَفِي اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ [o[إِلَّا]] بِاللَّهِ الْعَلِيِّ الْعَظِيمِ. بِسْمِ اللَّهِ عَلَىٰ دِينِي [o[وَعَلَىٰ]] نَفْسِي [o[وَعَلَىٰ]] [o[أَوْلَادِي]]، بِسْمِ اللَّهِ عَلَىٰ مَالِي [o[وَعَلَىٰ]] [o[أَهْلِي]]، بِسْمِ اللَّهِ عَلَىٰ كُلِّ شَيْءٍ [o[أَعْ]][q[طَ]]انِيهِ رَبِّي. بِسْمِ اللَّهِ رَبِّ [l[السَّ]]مَاوَاتِ [l[السَّ]][q[بْ]]عِ وَرَبِّ الْأَرَضِينَ [l[السَّ]][q[بْ]]عِ وَرَبِّ الْعَرْشِ الْعَظِيمِ. بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ [l[اسْ]]مِهِ شَيْ[a[ءٌ]] [a[فِ]]ي الْأَرْضِ وَلَا فِي [l[السَّ]]مَاءِ وَهُوَ [l[السَّ]]مِيعُ الْعَلِيمُ (٣ مرات). بِسْمِ اللَّهِ خَيْرِ [o[الْأَسْمَاءِ]] فِي الْأَرْضِ وَفِي [l[السَّ]]مَاءِ، بِسْمِ اللَّهِ [l[افْ]]تَتَحْتُ وَبِهِ [o[أَخْ]]تَتِمُ، [o[وَعَلَى]] اللَّهِ [p[تَوَكَّلْتُ]]",
                transliteration = "Bismillāh, wa billāh, wa minallāh, wa ilallāh, wa ‘alallāh, wa fillāh, wa lā ḥaula wa lā quwwata illā billāhil-‘aliyyil-‘aẓīm. Bismillāhi ‘alā dīnī wa ‘alā nafsī wa ‘alā aulādī, Bismillāhi ‘alā mālī wa ‘alā ahlī, Bismillāhi ‘alā kulli syai’in a‘ṭhānīhi rabbī. Bismillāhi rabbis-samāwātis-sab‘i wa rabbil-araḍīnas-sab‘i wa rabbil-‘arsyil-‘aẓīm. Bismillāhilladzī lā yaḍurru ma‘asmihī syai’un fil-arḍi wa lā fis-samā’i wa huwas-samī‘ul-‘alīm (3x). Bismillāhi khairil-asmā’i fil-arḍi wa fis-samā’, Bismillāhiftataḥtu wa bihī akhtatimu, wa ‘alallāhi tawakkaltu.",
                translationId = "Dengan nama Allah, bersama Allah, dari Allah, kepada Allah, berserah kepada Allah, di dalam perlindungan Allah, dan tiada daya serta kekuatan melainkan dengan pertolongan Allah Yang Mahatinggi lagi Mahaagung. Bismillah atas agamaku, diriku, dan anak-anakku. Bismillah atas hartaku dan keluargaku. Bismillah atas segala sesuatu yang dianugerahkan Tuhanku kepadaku. Bismillah Tuhan pemilik tujuh lapis langit, Tuhan pemilik tujuh lapis bumi, dan Tuhan Pemilik 'Arsy yang agung. Bismillah yang bersama nama-Nya tiada sesuatu pun di bumi maupun di langit yang dapat mendatangkan bahaya, dan Dia Maha Mendengar lagi Maha Mengetahui (3 kali). Dengan nama Allah sebaik-baik nama di bumi dan di langit, dengan nama Allah aku membuka dan dengan nama-Nya aku mengakhiri, dan kepada Allah aku bertawakal.",
                translationEn = "In the name of Allah, by Allah, from Allah, to Allah, upon Allah, in Allah, and there is no power nor might except by Allah the High, the Great. In the name of Allah upon my religion, myself, and my children...",
                repeatCount = 1,
                sourceNote = "Hizib An-Nawawi",
                fadhilah = "Melenyapkan keresahan jiwa, menolak racun dan penyakit bahaya, serta mengundang pertolongan Rabb pencipta langit dan bumi."
            ),
            DzikirItem(
                id = "nawawi_03",
                category = DzikirCategory.HIZIB_NAWAWI,
                orderNumber = 3,
                title = "Hizib An-Nawawi - Bagian 3: Tawakkal, Doa Khusyuk & Penyerahan Diri",
                arabicText = "اللَّهُ، اللَّهُ، اللَّهُ رَبِّي لَا أُشْرِكُ بِهِ أَحَدًا. اللَّهُ، اللَّهُ، اللَّهُ رَبِّي لَا إِلَٰهَ إِلَّا هُوَ. اللَّهُ، اللَّهُ، اللَّهُ أَعَزُّ وَأَجَلُّ وَأَكْبَرُ مِمَّا أَخَافُ وَأَحْذَرُ. عَزَّ جَارُكَ، وَجَلَّ ثَنَاؤُكَ، وَتَقَدَّسَتْ أَسْمَاؤُكَ، وَلَا إِلَٰهَ غَيْرُكَ. اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ شَرِّ نَفْسِي، وَمِنْ شَرِّ كُلِّ سُلْطَانٍ شَدِيدٍ، وَمِنْ شَرِّ كُلِّ شَيْطَانٍ مَرِيدٍ، وَمِنْ شَرِّ كُلِّ جَبَّارٍ عَنِيدٍ، وَمِنْ شَرِّ قَضَاءِ السُّوءِ، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا، إِنَّ رَبِّي عَلَىٰ صِرَاطٍ مُّسْتَقِيمٍ",
                tajwidTags = "اللَّهُ، اللَّهُ، اللَّهُ رَبِّي [o[لَا]] [o[أُشْرِكُ]] بِهِ [p[أَحَدًا]]. اللَّهُ، اللَّهُ، اللَّهُ رَبِّي [o[لَا]] [o[إِلَٰهَ]] [o[إِلَّا]] هُوَ. اللَّهُ، اللَّهُ، اللَّهُ [o[أَعَزُّ]] [o[وَأَجَلُّ]] [o[وَأَكْ]]بَرُ [g[مِمَّا]] [o[أَخَافُ]] [o[وَأَحْ]]ذَرُ. عَ[g[زَّ]] جَارُكَ، وَجَ[g[لَّ]] ثَنَا[o[ؤُكَ]]، وَتَ[q[قَ]][g[دَّ]]سَتْ [o[أَسْمَاؤُكَ]]، [o[وَلَا]] [o[إِلَٰهَ]] غَيْرُكَ. [g[اللَّ]]هُمَّ [g[إِنِّي]] أَعُوذُ بِكَ [f[مِن]] [f[شَ]]رِّ نَفْسِي، وَ[f[مِن]] [f[شَ]]رِّ كُلِّ سُلْطَانٍ شَدِيدٍ، وَ[f[مِن]] [f[شَ]]رِّ كُلِّ شَيْطَانٍ مَرِيدٍ، وَ[f[مِن]] [f[شَ]]رِّ كُلِّ جَبَّارٍ عَنِيدٍ، وَ[f[مِن]] [f[شَ]]رِّ [q[قَ]]ضَاءِ [l[السُّ]][o[وءِ]]، وَ[f[مِن]] [f[شَ]]رِّ كُلِّ دَ[o[ابَّةٍ]] [f[أَنتَ]] [o[آخِذٌ]] بِنَاصِيَتِهَا، [g[إِنَّ]] رَبِّي عَلَىٰ صِرَا[a[طٍ]] [a[مُّ]][p[سْتَقِيمٍ]]",
                transliteration = "Allāhu, Allāhu, Allāhu rabbī lā usyriku bihī aḥadā. Allāhu, Allāhu, Allāhu rabbī lā ilāha illā huw. Allāhu, Allāhu, Allāhu a‘azzu wa ajallu wa akbaru mimmā akhāfu wa aḥdzar. ‘Azza jāruk, wa jalla tsanā’uk, wa taqaddasat asmā’uk, wa lā ilāha ghairuk. Allāhumma innī a‘ūdzu bika ming syarri nafsī, wa ming syarri kulli sulṭhānin syadīd, wa ming syarri kulli syaithānim marīd, wa ming syarri kulli jabbārin ‘anīd, wa ming syarri qaḍā’is-sū’, wa ming syarri kulli dābbatin angta ākhidzum bi-nāṣiyatihā, inna rabbī ‘alā ṣirāṭhim mustaqīm.",
                translationId = "Allah, Allah, Allah adalah Tuhanku, aku tidak menyekutukan-Nya dengan seorang pun. Allah, Allah, Allah adalah Tuhanku, tiada tuhan selain Dia. Allah, Allah, Allah Mahaperkasa, Mahaagung, dan Mahabesar dari segala yang aku takuti dan aku cemaskan. Sungguh mulia perlindungan-Mu, Mahaagung pujian-Mu, Mahasuci nama-nama-Mu, dan tiada tuhan selain Engkau. Ya Allah, sesungguhnya aku berlindung kepada-Mu dari keburukan diriku, kejahatan setiap penguasa yang kejam, kejahatan setan yang durhaka, kejahatan orang sombong yang membangkang, keburukan takdir yang buruk, dan dari kejahatan setiap makhluk melata yang Engkau pegang ubun-ubunnya. Sesungguhnya Tuhanku berada di atas jalan yang lurus.",
                translationEn = "Allah, Allah, Allah is my Lord, I associate no one with Him. Allah, Allah, Allah is my Lord, there is no deity except Him. Allah, Allah, Allah is more Mighty, more Glorious and Tremendous than all that I fear and dread...",
                repeatCount = 1,
                sourceNote = "Hizib An-Nawawi",
                fadhilah = "Menghilangkan rasa takut kepada penguasa zalim, jin jahat, binatang berbisa, dan takdir buruk."
            ),
            DzikirItem(
                id = "nawawi_04",
                category = DzikirCategory.HIZIB_NAWAWI,
                orderNumber = 4,
                title = "Hizib An-Nawawi - Bagian 4: Benteng Enam Penjuru Al-Ikhlas",
                arabicText = "وَأُقَدِّمُ بَيْنَ يَدَيَّ وَأَيْدِيهِمْ، وَأَيْدِي مَنْ أَحَاطَتْهُ عِنَايَتِي وَشَمِلَتْهُ إِحَاطَتِي: بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ (قُلْ هُوَ اللَّهُ أَحَدٌ ۝ اللَّهُ الصَّمَدُ ۝ لَمْ يَلِدْ وَلَمْ يُولَدْ ۝ وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ)\\nوَمِثْلُ ذَلِكَ عَنْ يَمِينِي وَأَيْمَانِهِمْ، وَمِثْلُ ذَلِكَ عَنْ شِمَالِي وَعَنْ شَمَائِلِهِمْ، وَمِثْلُ ذَلِكَ مِنْ أَمَامِي وَأَمَامِهِمْ، وَمِثْلُ ذَلِكَ مِنْ خَلْفِي وَمِنْ خَلْفِهِمْ، وَمِثْلُ ذَلِكَ مِنْ فَوْقِي وَمِنْ فَوْقِهِمْ، وَمِثْلُ ذَلِكَ مِنْ تَحْتِي وَمِنْ تَحْتِهِمْ، وَمِثْلُ ذَلِكَ مُحِيطٌ بِي وَبِهِمْ وَبِمَا أَحَطْنَا بِهِ",
                tajwidTags = "[o[وَأُقَ]][g[دِّ]]مُ بَيْنَ يَدَ[g[يَّ]] [o[وَأَيْدِيهِمْ]]، [o[وَأَيْدِي]] مَنْ [o[أَحَاطَتْهُ]] عِنَايَتِي وَشَمِلَتْهُ [o[إِحَاطَتِي]]: بِسْمِ اللَّهِ [l[ال]][l[رَّ]]حْمَٰنِ [l[ال]][p[رَّحِيمِ]] (قُلْ هُوَ اللَّهُ [q[أَحَدٌ]] ۝ اللَّهُ [l[الصَّ]]مَدُ ۝ لَمْ [q[يَلِدْ]] وَلَمْ [q[يُولَدْ]] ۝ وَلَمْ يَكُ[u[ن]] [u[لَّ]]هُ كُفُ[a[وًا]] [a[أَ]]حَدٌ)\\nوَمِثْلُ ذَٰلِكَ عَنْ يَمِينِي [o[وَأَيْمَانِهِمْ]]، وَمِثْلُ ذَٰلِكَ عَنْ شِمَالِي وَعَنْ شَمَا[o[ئِلِهِمْ]]، وَمِثْلُ ذَٰلِكَ مِنْ [o[أَمَامِي]] [o[وَأَمَامِهِمْ]]، وَمِثْلُ ذَٰلِكَ مِنْ خَلْفِي وَمِنْ خَلْفِهِمْ، وَمِثْلُ ذَٰلِكَ مِنْ فَوْقِي وَمِنْ فَوْقِهِمْ، وَمِثْلُ ذَٰلِكَ مِنْ تَحْتِي وَمِنْ تَحْتِهِمْ، وَمِثْلُ ذَٰلِكَ مُحِي[q[طٌ]] بِي وَبِهِمْ وَبِمَا [o[أَحَ]][q[طْ]]نَا [p[بِهِ]]",
                transliteration = "Wa uqaddimu baina yadayya wa aidīhim, wa aidī man aḥāṭhat-hu ‘ināyatī wa syamilat-hu iḥāṭhatī: Bismillāhir-raḥmānir-raḥīm (Qul huwallāhu aḥad, Allāhuṣ-ṣamad, lam yalid wa lam yūlad, wa lam yakul lahū kufuwan aḥad).\\nWa mitslu dzālika ‘ay yamīnī wa aimānihim, wa mitslu dzālika ‘an syimālī wa ‘an syamā’ilihim, wa mitslu dzālika min amāmī wa amāmihim, wa mitslu dzālika ming khalfī wa ming khalfihim, wa mitslu dzālika min fauqī wa min fauqihim, wa mitslu dzālika min taḥtī wa min taḥtihim, wa mitslu dzālika muḥīṭhum bī wa bihim wa bimā aḥaṭhnā bih.",
                translationId = "Dan aku persembahkan di hadapanku dan di hadapan mereka, serta di hadapan orang-orang yang tercakup dalam perhatianku dan pemeliharaanku: Dengan nama Allah Yang Maha Pengasih lagi Maha Penyayang: 'Katakanlah: Dialah Allah Yang Maha Esa, Allah tempat bergantung segala sesuatu, Dia tidak beranak dan tidak pula diperanakkan, dan tidak ada sesuatu pun yang setara dengan Dia' (QS. Al-Ikhlas: 1-4).\\nDan serupa dengan itu dari sebelah kananku dan kanan mereka; dan serupa dengan itu dari sebelah kiriku dan kiri mereka; dan serupa dengan itu dari hadapanku dan hadapan mereka; dan serupa dengan itu dari belakangku dan belakang mereka; dan serupa dengan itu dari atasku dan atas mereka; dan serupa dengan itu dari bawahku dan bawah mereka; dan serupa dengan itu meliputi diriku, meliputi mereka, dan meliputi apa yang kami lingkupi.",
                translationEn = "And I place before me and before them, and before those enveloped by my care: Surah Al-Ikhlas; and the like of that on my right and their right; and the like of that on my left and their left; and the like of that in front of me and in front of them; and the like of that behind me and behind them; and the like of that above me and above them; and the like of that beneath me and beneath them; and the like of that encompassing me and them...",
                repeatCount = 1,
                sourceNote = "Hizib An-Nawawi Al-Imam An-Nawawi",
                fadhilah = "Mendirikan benteng kubah tauhid enam penjuru yang kokoh melindungi keluarga, tempat tinggal, dan keturunan."
            ),
            DzikirItem(
                id = "nawawi_05",
                category = DzikirCategory.HIZIB_NAWAWI,
                orderNumber = 5,
                title = "Hizib An-Nawawi - Bagian 5: Doa Perlindungan Rahmat & Tirai Ilahi",
                arabicText = "اللَّهُمَّ إِنِّي أَسْأَلُكَ لِي وَلَهُمْ مِنْ خَيْرِكَ بِخَيْرِكَ الَّذِي لَا يَمْلِكُهُ غَيْرُكَ. اللَّهُمَّ اجْعَلْنِي وَإِيَّاهُمْ فِي عِبَادِكَ وَعِيَاذِكَ، وَجِوَارِكَ وَأَمَانِكَ، وَحِزْبِكَ وَحِرْزِكَ، وَكَنَفِكَ وَسِتْرِكَ، مِنْ كُلِّ شَيْطَانٍ وَسُلْطَانٍ، وَإِنْسٍ وَجَانٍّ، وَبَاغٍ وَحَاسِدٍ، وَسَبُعٍ وَحَيَّةٍ وَعَقْرَبٍ، وَمِنْ شَرِّ كُلِّ دَابَّةٍ أَنْتَ آخِذٌ بِنَاصِيَتِهَا، إِنَّ رَبِّي عَلَىٰ صِرَاطٍ مُّسْتَقِيمٍ",
                tajwidTags = "[g[اللَّ]]هُمَّ [g[إِنِّي]] [o[أَسْأَلُكَ]] لِي وَلَهُم [f[مِّن]] خَيْرِكَ بِخَيْرِكَ الَّذِي لَا يَمْلِكُهُ غَيْرُكَ. [g[اللَّ]]هُمَّ [l[ا]][q[جْ]]عَلْنِي [o[وَإِيَّاهُمْ]] فِي عِبَادِكَ وَعِيَاذِكَ، وَجِوَارِكَ [o[وَأَمَانِكَ]]، وَحِ[q[زْ]]بِكَ وَحِرْزِكَ، وَكَنَفِكَ وَسِ[q[تْرِ]]كَ، [f[مِن]] كُلِّ شَيْطَانٍ وَسُلْطَانٍ، [o[وَإِنسٍ]] [a[وَ]][o[جَانٍّ]]، وَبَا[a[غٍ]] [a[وَ]]حَاسِدٍ، وَسَبُ[a[عٍ]] [a[وَ]]حَ[g[يَّ]][a[ةٍ]] [a[وَ]]عَ[q[قْ]]رَبٍ، وَ[f[مِن]] [f[شَ]]رِّ كُلِّ دَ[o[ابَّةٍ]] [f[أَنتَ]] [o[آخِذٌ]] بِنَاصِيَتِهَا، [g[إِنَّ]] رَبِّي عَلَىٰ صِرَا[a[طٍ]] [a[مُّ]][p[سْتَقِيمٍ]]",
                transliteration = "Allāhumma innī as’aluka lī wa lahum min khairika bi-khairikal-ladzī lā yamlikuhū ghairuk. Allāhummāj-‘alnī wa iyyāhum fī ‘ibādika wa ‘iyādzika, wa jiwārika wa amānik, wa ḥizbika wa ḥirzik, wa kanafika wa sitrik, ming kulli syaithāniw wa sulṭhān, wa insiw wa jān, wa bāghiw wa ḥāsid, wa sabu‘iw wa ḥayyatiw wa ‘aqrab, wa ming syarri kulli dābbatin angta ākhidzum bi-nāṣiyatihā, inna rabbī ‘alā ṣirāṭhim mustaqīm.",
                translationId = "Ya Allah, sesungguhnya aku memohon untukku dan untuk mereka dari kebaikan-Mu dengan kebaikan-Mu yang tidak dimiliki oleh selain-Mu. Ya Allah, jadikanlah aku dan mereka berada dalam barisan hamba-hamba-Mu, perlindungan-Mu, tetangga-Mu, keamanan-Mu, golongan-Mu, benteng perisai-Mu, naungan-Mu, dan tirai penutup-Mu dari kejahatan setiap setan dan penguasa tiran, manusia dan jin, pemberontak dan pendengki, binatang buas, ular, dan kalajengking, serta dari kejahatan setiap makhluk melata yang Engkau pegang ubun-ubunnya. Sesungguhnya Tuhanku berada di atas jalan yang lurus.",
                translationEn = "O Allah, I ask You for myself and for them from Your goodness... Place me and them in Your protection, sanctuary, guardianship, and security, and under Your cover...",
                repeatCount = 1,
                sourceNote = "Hizib An-Nawawi",
                fadhilah = "Menjaga keluarga dan sahabat dari marabahaya hewani, racun berbisa, dan fitnah manusia."
            ),
            DzikirItem(
                id = "nawawi_06",
                category = DzikirCategory.HIZIB_NAWAWI,
                orderNumber = 6,
                title = "Hizib An-Nawawi - Bagian 6: Tujuh Tingkat Kemuliaan Tauhid & Penutup Doa",
                arabicText = "حَسْبِيَ الرَّبُّ مِنَ الْمَرْبُوبِينَ، حَسْبِيَ الْخَالِقُ مِنَ الْمَخْلُوقِينَ، حَسْبِيَ الرَّازِقُ مِنَ الْمَرْزُوقِينَ، حَسْبِيَ السَّاتِرُ مِنَ الْمَسْتُورِينَ، حَسْبِيَ النَّاصِرُ مِنَ الْمَنْصُورِينَ، حَسْبِيَ الْقَاهِرُ مِنَ الْمَقْهُورِينَ، حَسْبِيَ الَّذِي هُوَ حَسْبِي، حَسْبِي مَنْ لَمْ يَزَلْ حَسْبِي، حَسْبِيَ اللَّهُ وَنِعْمَ الْوَكِيلُ، حَسْبِيَ اللَّهُ مِنْ جَمِيعِ خَلْقِهِ. إِنَّ وَلِيِّيَ اللَّهُ الَّذِي نَزَّلَ الْكِتَابَ ۖ وَهُوَ يَتَوَلَّى الصَّالِحِينَ. وَإِذَا قَرَأْتَ الْقُرْآنَ جَعَلْنَا بَيْنَكَ وَبَيْنَ الَّذِينَ لَا يُؤْمِنُونَ بِالْآخِرَةِ حِجَابًا مَّسْتُورًا ۝ وَجَعَلْنَا عَلَىٰ قُلُوبِهِمْ أَكِنَّةً أَن يَفْقَهُوهُ وَفِي آذَانِهِمْ وَقْرًا ۚ وَإِذَا ذَكَرْتَ رَبَّكَ فِي الْقُرْآنِ وَحْدَهُ وَلَّوْا عَلَىٰ أَدْبَارِهِمْ نُفُورًا. فَإِن تَوَلَّوْا فَقُلْ حَسْبِيَ اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ (٧ مرات). وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ الْعَلِيِّ الْعَظِيمِ. وَصَلَّى اللَّهُ عَلَىٰ سَيِّدِنَا مُحَمَّدٍ وَعَلَىٰ آلِهِ وَصَحْبِهِ وَسَلَّمَ تَسْلِيمًا كَثِيرًا إِلَىٰ يَوْمِ الدِّينِ، وَالْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
                tajwidTags = "حَسْبِيَ [l[الرَّ]]بُّ مِنَ الْمَرْبُوبِينَ، حَسْبِيَ الْخَالِقُ مِنَ الْمَخْلُوقِينَ، حَسْبِيَ [l[الرَّ]]ازِقُ مِنَ الْمَرْزُوقِينَ، حَسْبِيَ [l[السَّ]]اتِرُ مِنَ الْمَسْتُورِينَ، حَسْبِيَ [l[النَّ]]اصِرُ مِنَ [p[الْمَنصُورِينَ]]، حَسْبِيَ الْقَاهِرُ مِنَ الْمَ[q[قْ]]هُورِينَ، حَسْبِيَ الَّذِي هُوَ حَسْبِي، حَسْبِي [a[مَن]] [u[لَّ]]مْ يَزَلْ حَسْبِي، حَسْبِيَ اللَّهُ وَنِعْمَ [p[الْوَكِيلُ]]، حَسْبِيَ اللَّهُ مِنْ جَمِيعِ خَلْقِهِ. [g[إِنَّ]] وَلِيِّيَ اللَّهُ الَّذِي [g[نَزَّ]]لَ الْكِتَابَ ۖ وَهُوَ يَتَوَلَّى [l[الصَّ]][p[الِحِينَ]]. [o[وَإِذَا]] قَرَ[o[أْتَ]] الْقُرْ[o[آنَ]] جَعَلْنَا بَيْنَكَ وَبَيْنَ الَّذِينَ لَا يُؤْمِنُونَ بِالْآخِرَةِ حِجَا[a[بًا]] [a[مَّ]][l[سْ]]تُورًا ۝ وَجَعَلْنَا عَلَىٰ قُلُوبِهِمْ [o[أَكِ]][g[نَّةً]] [a[أَن]] [a[يَ]][q[فْ]]قَهُوهُ وَفِي [o[آذَانِهِمْ]] وَ[q[قْ]][a[رًا]] ۚ [o[وَإِذَا]] ذَكَرْتَ رَبَّكَ فِي الْقُرْ[o[آنِ]] وَحْدَهُ وَلَّوْا عَلَىٰ [o[أَدْبَارِهِمْ]] [p[نُفُورًا]]. فَ[a[إِن]] [a[تَ]]وَلَّوْا فَقُلْ حَسْبِيَ اللَّهُ [o[لَا]] [o[إِلَٰهَ]] [o[إِلَّا]] هُوَ ۖ عَلَيْهِ تَوَكَّلْتُ ۖ وَهُوَ رَبُّ الْعَرْشِ [p[الْعَظِيمِ]] (٧ مرات). وَلَا حَوْلَ وَلَا قُوَّةَ [o[إِلَّا]] بِاللَّهِ الْعَلِيِّ الْعَظِيمِ. وَصَلَّى اللَّهُ عَلَىٰ سَيِّدِنَا مُحَ[g[مَّ]]دٍ [o[وَعَلَىٰ]] [o[آلِهِ]] وَصَحْبِهِ وَسَلَّمَ تَسْلِي[f[مًا]] [f[كَ]]ثِي[a[رًا]] [o[إِلَىٰ]] يَوْمِ [l[الدِّ]][p[ينِ]]، وَالْحَمْدُ لِلَّهِ رَبِّ [p[الْعَالَمِينَ]]",
                transliteration = "Ḥasbiyar-rabbu minal-marbūbīn, ḥasbiyal-khāliqu minal-makhlūqīn, ḥasbiyar-rāziqu minal-marzūqīn, ḥasbiyas-sātiru minal-mastūrīn, ḥasbiyan-nāṣiru minal-manṣūrīn, ḥasbiyal-qāhiru minal-maqhūrīn, ḥasbiyal-ladzī huwa ḥasbī, ḥasbī mal lam yazal ḥasbī, ḥasbiyallāhu wa ni‘mal-wakīl, ḥasbiyallāhu min jamī‘i khalqih. Inna waliyyiyallāhul-ladzī nazzalal-kitāba wa huwa yatawallash-ṣāliḥīn. Wa idzā qara’tal-Qur’āna ja‘alnā bainaka wa bainal-ladzīna lā yu’minūna bil-ākhirati ḥijābam mastūrā. Wa ja‘alnā ‘alā qulūbihim akinnatan ay yafqahūhu wa fī ādzānihim waqrā, wa idzā dzakarta rabbaka fil-Qur’āni waḥdahū wallau ‘alā adbārihim nufūrā. Fa in tawallau fa qul ḥasbiyallāhu lā ilāha illā huwa, ‘alaihi tawakkaltu wa huwa rabbul-‘arsyil-‘aẓīm (7x). Wa lā ḥaula wa lā quwwata illā billāhil-‘aliyyil-‘aẓīm. Wa ṣallallāhu ‘alā sayyidinā Muḥammadiw wa ‘alā ālihī wa ṣaḥbihī wa sallama taslīman katsīran ilā yaumid-dīn, wal-ḥamdu lillāhi rabbil-‘ālamīn.",
                translationId = "Cukuplah Tuhan bagiku daripada sekalian yang dipertuan; cukuplah Sang Pencipta bagiku daripada sekalian makhluk; cukuplah Sang Pemberi Rezeki bagiku daripada sekalian yang diberi rezeki; cukuplah Sang Penutup Aib bagiku daripada sekalian yang ditutupi aibnya; cukuplah Sang Penolong bagiku daripada sekalian yang ditolong; cukuplah Sang Penunduk bagiku daripada sekalian yang ditundukkan; cukuplah Dzat yang Dialah Pencukup bagiku; cukuplah Dzat yang senantiasa mencukupiku; cukuplah Allah bagiku dan Dialah sebaik-baik Pelindung; cukuplah Allah bagiku dari seluruh makhluk-Nya. Sesungguhnya pelindungku adalah Allah yang telah menurunkan Kitab Suci, dan Dia melindungi orang-orang saleh... Maka jika mereka berpaling maka katakanlah: 'Cukuplah Allah bagiku, tidak ada tuhan selain Dia, hanya kepada-Nya aku bertawakal dan Dia adalah Tuhan pemilik Arsy yang agung' (7 kali). Dan tiada daya serta upaya melainkan dengan pertolongan Allah Yang Mahatinggi lagi Mahaagung.",
                translationEn = "Sufficient for me is the Lord over the subordinates; sufficient for me is the Creator over the created; sufficient for me is the Provider over the provided... Sufficient for me is Allah, and He is the best Disposer of affairs. Sufficient for me is Allah from all of His creation... But if they turn away, say: 'Sufficient for me is Allah; there is no deity except Him. On Him I have relied, and He is the Lord of the Great Throne' (7 times)...",
                repeatCount = 1,
                sourceNote = "Penutup Sempurna Hizib An-Nawawi karya Al-Imam An-Nawawi",
                fadhilah = "Mencapai ketenangan batin mutlak dan keselamatan sejati dalam perlindungan dan kecukupan Allah SWT."
            )"""

print("Nawawi chunk ready.")
