package com.quranplus.app.features.gharib.domain

data class GharibReading(
    val id: Int,
    val categoryId: String,
    val categoryTitle: String,
    val surahNumber: Int,
    val surahName: String,
    val ayahNumber: Int,
    val pageNumber: Int,
    val wordSnippetArabic: String,
    val fullAyahArabic: String,
    val pronunciationGuide: String,
    val writtenVsSpoken: String,
    val explanation: String,
    val ruleType: GharibType
)

enum class GharibType {
    NUN_WIQAYAH,
    AYAT_SAJDAH,
    SIFIR_MUSTADIR,
    SIFIR_MUSTATIL,
    SAKTAH,
    IMALAH,
    ISYMAM,
    TASHIL,
    NAQL
}

object GharibDataRepository {
    const val RECORD_LEVEL_REVIEW_COMPLETE = true

    val ALL_GHARIB_READINGS: List<GharibReading> = listOf(
        GharibReading(
            id = 1,
            categoryId = "IMALAH",
            categoryTitle = "Imalah (الإمالة)",
            surahNumber = 11,
            surahName = "Hud",
            ayahNumber = 41,
            pageNumber = 226,
            wordSnippetArabic = "مَجْرٰ۪ىهَا",
            fullAyahArabic = "وَقَالَ ارْكَبُوا فِيهَا بِسْمِ اللَّهِ مَجْرٰ۪ىهَا وَمُرْسَاهَا ۚ إِنَّ رَبِّي لَغَفُورٌ رَحِيمٌ",
            pronunciationGuide = "Dibaca: Maj-ree-haa (bunyi 're' seperti pada kata 'sate' / 'lele')",
            writtenVsSpoken = "Tertulis: مَجْرَاهَا ➔ Dibaca: مَجْرِيْهَا (Majreehaa)",
            explanation = "Imalah adalah memiringkan bunyi fathah ke arah kasrah dan alif ke arah ya'. Dalam Qira'at Imam 'Ashim riwayat Hafs jalur Syathibiyyah, hanya ada satu tempat imalah yaitu pada kata 'majraahaa' di surat Hud ayat 41.",
            ruleType = GharibType.IMALAH
        ),
        GharibReading(
            id = 2,
            categoryId = "ISYMAM",
            categoryTitle = "Isymam (الإشمام)",
            surahNumber = 12,
            surahName = "Yusuf",
            ayahNumber = 11,
            pageNumber = 236,
            wordSnippetArabic = "لَا تَأْمَ۫نَّا",
            fullAyahArabic = "قَالُوا يَا أَبَانَا مَا لَكَ لَا تَأْمَ۫نَّا عَلَىٰ يُوسُفَ وَإِنَّا لَهُ لَنَاصِحُونَ",
            pronunciationGuide = "Dibaca: Laa ta'mannaa (memoncongkan bibir tanpa suara saat dengung nun)",
            writtenVsSpoken = "Asal kata: لَا تَأْمَنُنَا ➔ Dibaca: Isymam (moncong bibir) atau Ikhtilas",
            explanation = "Isymam adalah memoncongkan kedua bibir ke depan tanpa mengeluarkan suara di pertengahan ghunnah nun bertasydid, sebagai isyarat adanya harakat dhammah asal yang diidghamkan. Alternatifnya boleh dibaca Ikhtilas (meringankan/mempercepat bacaan dhammah).",
            ruleType = GharibType.ISYMAM
        ),
        GharibReading(
            id = 3,
            categoryId = "TASHIL",
            categoryTitle = "Tashil (التسهيل)",
            surahNumber = 41,
            surahName = "Fussilat",
            ayahNumber = 44,
            pageNumber = 481,
            wordSnippetArabic = "ءَا۬عْجَمِيٌّ",
            fullAyahArabic = "وَلَوْ جَعَلْنَاهُ قُرْآنًا أَعْجَمِيًّا لَقَالُوا لَوْلَا فُصِّلَتْ آيَاتُهُ ۖ ءَاعْجَمِيٌّ وَعَرَبِيٌّ",
            pronunciationGuide = "Dibaca: Aa-a'jamiyyun (hamzah kedua dibaca lunak antara hamzah dan alif)",
            writtenVsSpoken = "Tertulis: أَأَعْجَمِيٌّ ➔ Dibaca: Tashil pada hamzah kedua",
            explanation = "Tashil artinya memudahkan, yaitu melunakkan pengucapan hamzah kedua di antara makhraj hamzah qath'i dan mad alif, tanpa menghentakkannya secara tajam. Wajib tashil dalam riwayat Hafs pada ayat ini.",
            ruleType = GharibType.TASHIL
        ),
        GharibReading(
            id = 4,
            categoryId = "NAQL",
            categoryTitle = "Naql (النقل)",
            surahNumber = 49,
            surahName = "Al-Hujurat",
            ayahNumber = 11,
            pageNumber = 516,
            wordSnippetArabic = "بِئْسَ الِاسْمُ",
            fullAyahArabic = "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا يَسْخَرْ قَوْمٌ مِنْ قَوْمٍ ... بِئْسَ الِاسْمُ الْفُسُوقُ بَعْدَ الْإِيمَانِ",
            pronunciationGuide = "Dibaca: Bi'sa-lismu (harakat kasrah hamzah washal berpindah ke lam sukun)",
            writtenVsSpoken = "Tertulis: بِئْسَ الاِسْمُ ➔ Dibaca: Bi'salismu (بِئْسَ لِسْمُ)",
            explanation = "Naql artinya memindahkan, yaitu memindahkan harakat kasrah dari hamzah washal ke huruf lam sukun sebelumnya. Sehingga saat dibaca washal berbunyi 'bi'salismu', dan jika memulai (ibtida') dari kata tersebut boleh membaca 'Al-ismu' atau 'Lismu'.",
            ruleType = GharibType.NAQL
        ),
        GharibReading(
            id = 5,
            categoryId = "SAKTAH",
            categoryTitle = "Saktah (السكتة) - Al-Kahf",
            surahNumber = 18,
            surahName = "Al-Kahf",
            ayahNumber = 1,
            pageNumber = 293,
            wordSnippetArabic = "عِوَجًا ۜ قَيِّمًا",
            fullAyahArabic = "الْحَمْدُ لِلَّهِ الَّذِي أَنْزَلَ عَلَىٰ عَبْدِهِ الْكِتَابَ وَلَمْ يَجْعَلْ لَهُ عِوَجًا ۜ (1) قَيِّمًا لِيُنْذِرَ بَأْسًا شَدِيدًا (2)",
            pronunciationGuide = "Dibaca: 'Iwajaa (berhenti 2 harakat tanpa nafas) lalu Qayyimaa",
            writtenVsSpoken = "Berhenti sejenak ~1 detik tanpa mengambil nafas lalu melanjutkan",
            explanation = "Saktah adalah berhenti sejenak tanpa bernafas selama kurang lebih 2 harakat dengan niat meneruskan bacaan. Saktah di sini bertujuan memisahkan makna agar tidak disangka bahwa kata 'qayyiman' adalah sifat dari 'iwajan'.",
            ruleType = GharibType.SAKTAH
        ),
        GharibReading(
            id = 6,
            categoryId = "SAKTAH",
            categoryTitle = "Saktah (السكتة) - Ya-Sin",
            surahNumber = 36,
            surahName = "Ya-Sin",
            ayahNumber = 52,
            pageNumber = 443,
            wordSnippetArabic = "مِنْ مَرْقَدِنَا ۜ هَٰذَا",
            fullAyahArabic = "قَالُوا يَا وَيْلَنَا مَنْ بَعَثَنَا مِنْ مَرْقَدِنَا ۜ هَٰذَا مَا وَعَدَ الرَّحْمَٰنُ وَصَدَقَ الْمُرْسَلُونَ",
            pronunciationGuide = "Dibaca: Mim-marqadinaa (saktah tanpa nafas) lalu Haadzaa",
            writtenVsSpoken = "Berhenti sejenak pada 'marqadinaa' sebelum ucapan malaikat 'haadzaa'",
            explanation = "Saktah di sini memisahkan ucapan orang kafir yang kebingungan ('Siapa yang membangkitkan kami dari tidur kami?') dengan jawaban dari para malaikat atau orang beriman ('Inilah yang dijanjikan oleh Yang Maha Pengasih').",
            ruleType = GharibType.SAKTAH
        ),
        GharibReading(
            id = 7,
            categoryId = "SAKTAH",
            categoryTitle = "Saktah (السكتة) - Al-Qiyamah",
            surahNumber = 75,
            surahName = "Al-Qiyamah",
            ayahNumber = 27,
            pageNumber = 578,
            wordSnippetArabic = "وَقِيلَ مَنْ ۜ رَاقٍ",
            fullAyahArabic = "كَلَّا إِذَا بَلَغَتِ التَّرَاقِيَ (26) وَقِيلَ مَنْ ۜ رَاقٍ (27)",
            pronunciationGuide = "Dibaca: Wa qiila man (saktah tanpa nafas) lalu raaq",
            writtenVsSpoken = "Nun sukun dibaca izhar jelas (tidak diidghamkan ke ra')",
            explanation = "Saktah pada 'man' mencegah terjadinya idgham bila ghunnah ke huruf 'ra', sehingga maknanya tetap jelas ('Dan dikatakan: Siapakah yang dapat menyembuhkan?') dan tidak tertukar dengan kata 'marraq' (penjual kuah/sup).",
            ruleType = GharibType.SAKTAH
        ),
        GharibReading(
            id = 8,
            categoryId = "SAKTAH",
            categoryTitle = "Saktah (السكتة) - Al-Mutaffifin",
            surahNumber = 83,
            surahName = "Al-Mutaffifin",
            ayahNumber = 14,
            pageNumber = 588,
            wordSnippetArabic = "كَلَّا ۖ بَلْ ۜ رَانَ",
            fullAyahArabic = "كَلَّا ۖ بَلْ ۜ رَانَ عَلَىٰ قُلُوبِهِمْ مَا كَانُوا يَكْسِبُونَ",
            pronunciationGuide = "Dibaca: Kallaa bal (saktah tanpa nafas) lalu raana",
            writtenVsSpoken = "Lam sukun dibaca izhar jelas (tidak diidghamkan ke ra')",
            explanation = "Saktah pada 'bal' menahan idgham ke huruf 'ra' agar tidak tertukar dengan kata 'barrana' (membuat kebaikan), melainkan tetap bermakna 'Sekali-kali tidak! Bahkan telah menutupi (noda dosa) hati mereka'.",
            ruleType = GharibType.SAKTAH
        ),
        GharibReading(
            id = 9,
            categoryId = "SIFIR_MUSTATIL",
            categoryTitle = "Sifir Mustatil (الصِّفْرُ الْمُسْتَطِيلُ)",
            surahNumber = 18,
            surahName = "Al-Kahf",
            ayahNumber = 38,
            pageNumber = 298,
            wordSnippetArabic = "لَّٰكِنَّا۠ هُوَ اللَّهُ رَبِّي",
            fullAyahArabic = "لَّٰكِنَّا۠ هُوَ اللَّهُ رَبِّي وَلَا أُشْرِكُ بِرَبِّي أَحَدًا",
            pronunciationGuide = "Washal: Laakinna Huwallahu (pendek) • Waqaf: Laakinnaa (panjang 2 harakat)",
            writtenVsSpoken = "Tanda bulatan lonjong (۠): Alif dibaca panjang saat waqaf, gugur saat washal",
            explanation = "Sifir Mustatil adalah tanda bulatan lonjong di atas huruf alif. Menunjukkan bahwa alif tersebut tetap dibaca panjang (mad thabi'i 2 harakat) jika waqaf (berhenti), namun gugur dan dibaca pendek jika washal (disambung).",
            ruleType = GharibType.SIFIR_MUSTATIL
        ),
        GharibReading(
            id = 10,
            categoryId = "SIFIR_MUSTATIL",
            categoryTitle = "Sifir Mustatil - Azh-Zhunuunaa",
            surahNumber = 33,
            surahName = "Al-Ahzab",
            ayahNumber = 10,
            pageNumber = 419,
            wordSnippetArabic = "الظُّنُونَا۠",
            fullAyahArabic = "إِذْ جَاءُوكُمْ مِنْ فَوْقِكُمْ وَمِنْ أَسْفَلَ مِنْكُمْ ... وَتَظُنُّونَ بِاللَّهِ الظُّنُونَا۠",
            pronunciationGuide = "Washal: Azh-Zhunuuna (pendek) • Waqaf: Azh-Zhunuunaa (panjang)",
            writtenVsSpoken = "Alif di akhir kata 'Azh-Zhunuunaa' gugur saat washal",
            explanation = "Terdapat tanda sifir mustatil di akhir ayat 10 surat Al-Ahzab. Jika menyambung bacaan ke ayat 11 maka alif dibaca pendek (Azh-zhunuuna idztuliya), namun jika waqaf di akhir ayat 10 dibaca panjang (Azh-zhunuunaa).",
            ruleType = GharibType.SIFIR_MUSTATIL
        ),
        GharibReading(
            id = 11,
            categoryId = "SIFIR_MUSTADIR",
            categoryTitle = "Sifir Mustadir (الصِّفْرُ الْمُسْتَدِيرُ)",
            surahNumber = 18,
            surahName = "Al-Kahf",
            ayahNumber = 23,
            pageNumber = 296,
            wordSnippetArabic = "لِشَا۟ىْءٍ",
            fullAyahArabic = "وَلَا تَقُولَنَّ لِشَا۟ىْءٍ إِنِّي فَاعِلٌ ذَٰلِكَ غَدًا",
            pronunciationGuide = "Dibaca: Li-syai-in (huruf alif tidak dibaca sama sekali baik washal maupun waqaf)",
            writtenVsSpoken = "Tertulis: لِشَاىْءٍ ➔ Dibaca: لِشَيْءٍ (Lisya-in)",
            explanation = "Sifir Mustadir adalah tanda bulatan bundar sempurna di atas huruf (alif/wawu/ya'). Huruf yang bertanda ini dianggap tidak ada (ziyadah) sehingga sama sekali tidak dibaca baik ketika washal maupun waqaf.",
            ruleType = GharibType.SIFIR_MUSTADIR
        ),
        GharibReading(
            id = 12,
            categoryId = "NUN_WIQAYAH",
            categoryTitle = "Nun Wiqayah / Nun Wasal (نُوْنُ الوَصْلِ)",
            surahNumber = 112,
            surahName = "Al-Ikhlas",
            ayahNumber = 1,
            pageNumber = 604,
            wordSnippetArabic = "أَحَدٌ ۨ اللَّهُ الصَّمَدُ",
            fullAyahArabic = "قُلْ هُوَ اللَّهُ أَحَدٌ (1) اللَّهُ الصَّمَدُ (2)",
            pronunciationGuide = "Washal: Qul huwallahu ahadunillaahush-shamad (muncul bunyi 'ni')",
            writtenVsSpoken = "Tertulis: أَحَدٌ اللَّهُ ➔ Dibaca washal: أَحَدُنِ اللَّهُ (Ahadunillaahu)",
            explanation = "Nun Wiqayah (Nun Wasal) terjadi ketika tanwin bertemu hamzah washal (alif lam). Jika kedua kata disambung (washal), tanwin dipecah menjadi harakat biasa ditambah nun kecil berharakat kasrah ('ni') untuk mencegah bertemunya dua huruf sukun.",
            ruleType = GharibType.NUN_WIQAYAH
        ),
        GharibReading(
            id = 13,
            categoryId = "AYAT_SAJDAH",
            categoryTitle = "Ayat Sajdah (آيات السجدة) - As-Sajdah",
            surahNumber = 32,
            surahName = "As-Sajdah",
            ayahNumber = 15,
            pageNumber = 416,
            wordSnippetArabic = "خَرُّوا سُجَّدًا وَسَبَّحُوا ۩",
            fullAyahArabic = "إِنَّمَا يُؤْمِنُ بِآيَاتِنَا الَّذِينَ إِذَا ذُكِّرُوا بِهَا خَرُّوا سُجَّدًا وَسَبَّحُوا بِحَمْدِ رَبِّهِمْ وَهُمْ لَا يَسْتَكْبِرُونَ ۩",
            pronunciationGuide = "Disunnahkan melakukan Sujud Tilawah (1 kali sujud) saat membaca atau mendengar ayat ini",
            writtenVsSpoken = "Simbol kubah/sajdah (۩) menandai ayat sajdah sunnah",
            explanation = "Terdapat 15 ayat sajdah dalam Al-Qur'an. Ketika sampai pada ayat ini, pembaca maupun pendengar disunnahkan untuk bersujud satu kali sebagai bentuk ketundukan dan ketaatan kepada firman Allah SWT.",
            ruleType = GharibType.AYAT_SAJDAH
        ),
        GharibReading(
            id = 14,
            categoryId = "AYAT_SAJDAH",
            categoryTitle = "Ayat Sajdah - Al-'Alaq",
            surahNumber = 96,
            surahName = "Al-'Alaq",
            ayahNumber = 19,
            pageNumber = 597,
            wordSnippetArabic = "وَاسْجُدْ وَاقْتَرِبْ ۩",
            fullAyahArabic = "كَلَّا لَا تُطِعْهُ وَاسْجُدْ وَاقْتَرِبْ ۩",
            pronunciationGuide = "Disunnahkan sujud tilawah setelah membaca ayat penutup surat Al-'Alaq ini",
            writtenVsSpoken = "Sujud 1 kali dengan membaca doa sujud tilawah",
            explanation = "Ayat ke-19 surat Al-'Alaq adalah perintah langsung dari Allah SWT untuk bersujud dan mendekatkan diri kepada-Nya, disunnahkan sujud tilawah baik di dalam maupun di luar shalat.",
            ruleType = GharibType.AYAT_SAJDAH
        )
    )
}
